//Here all maps in the game are listed (for now only one)
import 'package:flutter/material.dart';
import 'package:kharazan/models/fields.dart';

class MapsToBePlayed {
  static List<Field> allMapsInTheGame = [
    _coliseumMap,
  ];
  static Field _coliseumMap = Field(
    mapNumber: 1,
    name: 'Coliseum',
    whiteColor: Colors.grey[200]!,
    blackColor: Colors.blueGrey,
    attackedBlackColor: Colors.red[400]!,
    attackedWhiteColor: Colors.red[200]!,
    limitX: 800,
    limitY: 800,
    fieldSpace: <FieldTile>[
      FieldTile(name: 'a1'),
      FieldTile(name: 'b1'),
      FieldTile(name: 'c1'),
      FieldTile(name: 'd1'),
      FieldTile(name: 'e1'),
      FieldTile(name: 'f1'),
      FieldTile(name: 'g1'),
      FieldTile(name: 'h1'),
      FieldTile(name: 'a2'),
      FieldTile(name: 'b2'),
      FieldTile(name: 'c2'),
      FieldTile(name: 'd2'),
      FieldTile(name: 'e2'),
      FieldTile(name: 'f2'),
      FieldTile(name: 'g2'),
      FieldTile(name: 'h2'),
      FieldTile(name: 'a3'),
      FieldTile(name: 'b3'),
      FieldTile(name: 'c3'),
      FieldTile(name: 'd3'),
      FieldTile(name: 'e3'),
      FieldTile(name: 'f3'),
      FieldTile(name: 'g3'),
      FieldTile(name: 'h3'),
      FieldTile(name: 'a4'),
      FieldTile(name: 'b4'),
      FieldTile(name: 'c4'),
      FieldTile(name: 'd4'),
      FieldTile(name: 'e4'),
      FieldTile(name: 'f4'),
      FieldTile(name: 'g4'),
      FieldTile(name: 'h4'),
      FieldTile(name: 'a5'),
      FieldTile(name: 'b5'),
      FieldTile(name: 'c5'),
      FieldTile(name: 'd5'),
      FieldTile(name: 'e5'),
      FieldTile(name: 'f5'),
      FieldTile(name: 'g5'),
      FieldTile(name: 'h5'),
      FieldTile(name: 'a6'),
      FieldTile(name: 'b6'),
      FieldTile(name: 'c6'),
      FieldTile(name: 'd6'),
      FieldTile(name: 'e6'),
      FieldTile(name: 'f6'),
      FieldTile(name: 'g6'),
      FieldTile(name: 'h6'),
      FieldTile(name: 'a7'),
      FieldTile(name: 'b7'),
      FieldTile(name: 'c7'),
      FieldTile(name: 'd7'),
      FieldTile(name: 'e7'),
      FieldTile(name: 'f7'),
      FieldTile(name: 'g7'),
      FieldTile(name: 'h7'),
      FieldTile(name: 'a8'),
      FieldTile(name: 'b8'),
      FieldTile(name: 'c8'),
      FieldTile(name: 'd8'),
      FieldTile(name: 'e8'),
      FieldTile(name: 'f8'),
      FieldTile(name: 'g8'),
      FieldTile(name: 'h8'),
    ],
  );

  static Field get coliseumMap => _coliseumMap;
}
